### ISSUE TITLE
Claim_Method_Click option does not work

### ISSUE THREAD

**Issue by amongla** [ANTFOR7717/AutoWaifuClaimerV3#13]
When CLAIM_METHOD_CLICK is set to true it should in theory react to emojis when available to claim. I have had it set to True for a few days and i have no idea why it did not work once.

**Comment by argoniseur** [comment]
Just to be sure, the rolls that it should claim have an emoji ?

**Comment by amongla** [comment]
Yes, i'll attach an image as an example.
![image](https://user-images.githubusercontent.com/99649819/157836878-dbb1b141-9454-4faf-b384-f9b180a6c457.png)
The heart emoji on the left was placed by mudae itself, while the reacted one was from the bot's. The bot doesn't get to claim the character because of this. I think when mudae puts an emoji, other emojis don't count until reacted with the same emoji.

**Comment by argoniseur** [comment]
Yes I have the problem even when I'm playing myself. When Mudae places an emoji, you have to react to it, can't place another one. Which error do you get ?

**Comment by amongla** [comment]
Couldn't find the error as i restarted the bot. Will send the error when i encounter it again

**Comment by amongla** [comment]
Nevermind, i found it. 
![image](https://user-images.githubusercontent.com/99649819/157842094-e3ad9249-10cd-4efe-ad0b-953cfc421de3.png)
It didn't even show an error. Am i getting something wrong? If there was no error to begin with, then this option only applies to lovelist, no?

**Comment by argoniseur** [comment]
Oh okay I see, that may be a mistake I made. The character was in love/likelist ? Or is it only a claim attempt because of a high kak value ?

**Comment by amongla** [comment]
It's a high kak claim attempt; i have yet to see it on a lovelist as this game is very random

**Comment by argoniseur** [comment]
Okay then it's a mistake I made. I'll push a commit to solve it, but you'll have to wait for the PR to be reviewed and accepted

**Comment by amongla** [comment]
No worries at all! Appreciate the help

**Comment by amongla** [comment]
![image](https://user-images.githubusercontent.com/99649819/157936214-e26433bd-82c3-435f-ba68-12b308e16af8.png)
Updating the situation. The bot does click on emojis, but only when the character is in the lovelist.

**Comment by amongla** [comment]
To leave a note for others, The claim react speed option only affects subjects in waifu_list/lovelist. I have increased the delay thinking it's for universal claims and the bot did not react in time for that matter.

**Comment by argoniseur** [comment]
Yup that's what I'm correcting. The last pull request add this whole 'claim if a high kak' logic but I forgot that the config had this setting
